// <auto-generated />
using System;
using System.Collections.Generic;
using LearnForge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LearnForge.Infrastructure.Migrations
{
    [DbContext(typeof(LearnForgeDbContext))]
    partial class LearnForgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "activity_type", new[] { "article", "code_challenge", "debug_challenge", "multiple_choice", "fill_in_blank", "code_ordering", "output_prediction" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "lesson_resource_type", new[] { "article", "video", "docs", "repos", "website" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "material_status", new[] { "draft", "published" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LearnForge.Domain.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("LessonId");

                    b.HasIndex("Type", "Prompt", "ContentJson")
                        .IsUnique();

                    b.ToTable("activities", null, t =>
                        {
                            t.HasCheckConstraint("CK_Activity_Order_Positive", "\"Order\" >= 1");

                            t.HasCheckConstraint("CK_Activity_Prompt_NotEmpty", "LENGTH(TRIM(\"Prompt\")) > 0");

                            t.HasCheckConstraint("CK_Activity_Title_NotEmpty", "LENGTH(TRIM(\"Title\")) > 0");
                        });
                });

            modelBuilder.Entity("LearnForge.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Settings", "LearnForge.Domain.Entities.Course.Settings#CourseSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("HeartsEnabled")
                                .HasColumnType("boolean");

                            b1.Property<int>("MaxHearts")
                                .HasColumnType("integer");

                            b1.Property<bool>("StreaksEnabled")
                                .HasColumnType("boolean");

                            b1.Property<bool>("WeeklyLeaderboardEnabled")
                                .HasColumnType("boolean");

                            b1.Property<int>("XpPerExercise")
                                .HasColumnType("integer");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("InstructorId");

                    b.ToTable("courses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Course_Title_NotEmpty", "LENGTH(TRIM(\"Title\")) > 0");
                        });
                });

            modelBuilder.Entity("LearnForge.Domain.Entities.CourseModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("CourseId", "Order")
                        .IsUnique();

                    b.ToTable("course_modules", null, t =>
                        {
                            t.HasCheckConstraint("CK_CourseModule_Order_Positive", "\"Order\" >= 1");

                            t.HasCheckConstraint("CK_CourseModule_Title_NotEmpty", "LENGTH(TRIM(\"Title\")) > 0");
                        });
                });

            modelBuilder.Entity("LearnForge.Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentMarkdown")
                        .HasColumnType("text");

                    b.Property<Guid>("CourseModuleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("CourseModuleId", "Order")
                        .IsUnique();

                    b.ToTable("lessons", null, t =>
                        {
                            t.HasCheckConstraint("CK_Lesson_Order_Positive", "\"Order\" >= 1");

                            t.HasCheckConstraint("CK_Lesson_Title_NotEmpty", "LENGTH(TRIM(\"Title\")) > 0");
                        });
                });

            modelBuilder.Entity("LearnForge.Domain.Entities.LessonResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("LessonId");

                    b.HasIndex("Title", "Url", "Type")
                        .IsUnique();

                    b.ToTable("lesson_resources", null, t =>
                        {
                            t.HasCheckConstraint("CK_LessonResource_Order_Positive", "\"Order\" >= 1");

                            t.HasCheckConstraint("CK_LessonResource_Title_NotEmpty", "LENGTH(TRIM(\"Title\")) > 0");

                            t.HasCheckConstraint("CK_LessonResource_Url_NotEmpty", "LENGTH(TRIM(\"Url\")) > 0");
                        });
                });

            modelBuilder.Entity("LearnForge.Domain.Entities.Activity", b =>
                {
                    b.HasOne("LearnForge.Domain.Entities.Lesson", null)
                        .WithMany("Activities")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LearnForge.Domain.Entities.CourseModule", b =>
                {
                    b.HasOne("LearnForge.Domain.Entities.Course", null)
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LearnForge.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("LearnForge.Domain.Entities.CourseModule", null)
                        .WithMany("Lessons")
                        .HasForeignKey("CourseModuleId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LearnForge.Domain.Entities.LessonResource", b =>
                {
                    b.HasOne("LearnForge.Domain.Entities.Lesson", null)
                        .WithMany("Resources")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LearnForge.Domain.Entities.Course", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("LearnForge.Domain.Entities.CourseModule", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("LearnForge.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
